name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
 
    # Run Contrast Scan to analyze securuity of jar    
    - name: Contrast Scan
      uses: Contrast-Security-OSS/contrastscan-action@v1
      with:
        artifact: spring-petclinic/target/spring-petclinic-1.5.1.jar
        
      env:
        CONTRAST__API__URL: "https://eval.contrastsecurity.com/Contrast"
        CONTRAST__API__USER_NAME: "demo.user@contrastsecurity.com"
        CONTRAST__API__ORGANIZATION_ID: "6a3073a5-5e68-40e5-9d7d-165340fff15a"
        CONTRAST__API__SERVICE_KEY: "QP5CWID33DRMKNV7"
        CONTRAST__API__API_KEY: "IMDq4X0K8BzCvwUt3iEyn0TV4Ti3loMD"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
