name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
