name: Maven CI/CD 

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
 
    # Run Contrast Scan to analyze securuity of jar    
    - name: Contrast Scan
      uses: Contrast-Security-OSS/contrastscan-action@v1
      with:
        artifact: "/home/runner/work/spring-petclinic/spring-petclinic/target/spring-petclinic-1.5.1.jar"
        api_url: "https://apptwo.contrastsecurity.com/Contrast"     
      env:
        CONTRAST__API__USER_NAME: "jeff.williams@contrastsecurity.com"
        CONTRAST__API__ORGANIZATION_ID: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
        CONTRAST__API__SERVICE_KEY: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
        CONTRAST__API__API_KEY: ${{ secrets.CONTRAST__API__API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
